# Generated by Django 5.2.3 on 2025-07-08 04:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPalabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estrella', models.BooleanField(default=False)),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabra_usuarios', to='dictionary.palabra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_palabras', to='accounts.usuario')),
            ],
            options={
                'db_table': 'Usuarios_Palabras',
                'unique_together': {('usuario', 'palabra')},
            },
        ),
    ]
