# Generated by Django 5.2.4 on 2025-08-09 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_usuariopalabra_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopalabra',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopalabra',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
