# Generated by Django 5.2.4 on 2025-07-08 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioGrupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guardado", models.BooleanField(default=False)),
                ("estudiando", models.BooleanField(default=False)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grupo_usuarios",
                        to="main.grupo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_grupos",
                        to="main.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "Usuarios_Grupos",
                "unique_together": {("usuario", "grupo")},
            },
        ),
    ]
