# Generated by Django 5.2.3 on 2025-07-20 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
        ('dictionary', '0004_alter_lectura_autor_alter_nota_autor_and_more'),
        ('groups', '0006_alter_grupo_autor_alter_usuariogrupo_usuario'),
        ('progress', '0002_alter_usuariopalabra_usuario'),
        ('tags', '0002_alter_etiqueta_autor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('moderator', 'Moderator')], default='user', max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
