# Generated by Django 5.2.7 on 2025-11-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_perfil_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tema',
            field=models.CharField(choices=[('Jouzu', 'Jouzu'), ('Marinate', 'Marinate'), ('Techno Punk', 'Techno Punk'), ('Space Cowboy', 'Space Cowboy'), ('Cyber Clock', 'Cyber Clock')], default='Jouzu', max_length=20),
        ),
    ]
