# Generated by Django 5.2.4 on 2025-07-07 23:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Palabras',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password_hash', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('moderator', 'Moderator')], default='user', max_length=10)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Significado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('significado', models.TextField(max_length=50)),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='significados', to='main.palabra')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='significados', to='main.usuario')),
            ],
            options={
                'db_table': 'Significados',
            },
        ),
        migrations.AddField(
            model_name='palabra',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabras', to='main.usuario'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(max_length=100)),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='main.palabra')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='main.usuario')),
            ],
            options={
                'db_table': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectura', models.CharField(max_length=50)),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='main.palabra')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='main.usuario')),
            ],
            options={
                'db_table': 'Lecturas',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='main.usuario')),
            ],
            options={
                'db_table': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=25)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='main.usuario')),
            ],
            options={
                'db_table': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='GrupoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiqueta_grupos', to='main.etiqueta')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_etiquetas', to='main.grupo')),
            ],
            options={
                'db_table': 'Grupos_Etiquetas',
                'unique_together': {('grupo', 'etiqueta')},
            },
        ),
        migrations.CreateModel(
            name='GrupoPalabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_palabras', to='main.grupo')),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabra_grupos', to='main.palabra')),
            ],
            options={
                'db_table': 'Grupos_Palabras',
                'unique_together': {('grupo', 'palabra')},
            },
        ),
        migrations.CreateModel(
            name='PalabraEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiqueta_palabras', to='main.etiqueta')),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabra_etiquetas', to='main.palabra')),
            ],
            options={
                'db_table': 'Palabras_Etiquetas',
                'unique_together': {('palabra', 'etiqueta')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioPalabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estrella', models.BooleanField(default=False)),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabra_usuarios', to='main.palabra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_palabras', to='main.usuario')),
            ],
            options={
                'db_table': 'Usuarios_Palabras',
                'unique_together': {('usuario', 'palabra')},
            },
        ),
    ]
