# Generated by Django 5.2.3 on 2025-07-08 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dictionary', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=25)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='accounts.usuario')),
            ],
            options={
                'db_table': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='GrupoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiqueta_grupos', to='tags.etiqueta')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_etiquetas', to='groups.grupo')),
            ],
            options={
                'db_table': 'Grupos_Etiquetas',
                'unique_together': {('grupo', 'etiqueta')},
            },
        ),
        migrations.CreateModel(
            name='PalabraEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiqueta_palabras', to='tags.etiqueta')),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabra_etiquetas', to='dictionary.palabra')),
            ],
            options={
                'db_table': 'Palabras_Etiquetas',
                'unique_together': {('palabra', 'etiqueta')},
            },
        ),
    ]
