# Generated by Django 5.2.4 on 2025-07-21 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_etiqueta_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiqueta',
            old_name='autor',
            new_name='usuario',
        ),
    ]
