# Generated by Django 5.2.4 on 2025-08-09 02:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_rename_autor_lectura_usuario_and_more'),
        ('groups', '0007_rename_autor_grupo_usuario'),
        ('tags', '0004_alter_grupoetiqueta_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grupoetiqueta',
            name='uniq_grupo_etiqueta_usuario',
        ),
        migrations.RemoveConstraint(
            model_name='palabraetiqueta',
            name='uniq_palabra_etiqueta_usuario',
        ),
        migrations.AlterUniqueTogether(
            name='grupoetiqueta',
            unique_together={('grupo', 'etiqueta', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='palabraetiqueta',
            unique_together={('palabra', 'etiqueta', 'usuario')},
        ),
    ]
