# Generated by Django 5.2.4 on 2025-08-09 02:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_remove_grupoetiqueta_uniq_grupo_etiqueta_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupoetiqueta',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='palabraetiqueta',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grupoetiqueta',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='palabraetiqueta',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
