# Generated by Django 5.2.7 on 2025-10-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_rename_created_at_grupoetiqueta_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='color',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
