# Generated by Django 5.2.7 on 2025-11-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_etiqueta_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='color',
            field=models.CharField(choices=[('0', 'Rojo'), ('1', 'Naranja'), ('2', 'Amarillo'), ('3', 'Verde'), ('4', 'Azul'), ('5', 'Indigo'), ('6', 'Morado'), ('7', 'Rosa'), ('8', 'Negro'), ('9', 'Gris'), ('neutral', 'Neutral')], default='neutral', max_length=10),
        ),
        migrations.DeleteModel(
            name='GrupoEtiqueta',
        ),
    ]
