# Generated by Django 5.2.7 on 2025-11-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0008_alter_etiqueta_color_delete_grupoetiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='color',
            field=models.CharField(choices=[('0', 'Main'), ('A', 'Rojo Subrayado'), ('AA', 'Rojo'), ('Aa', 'Rojo Oscuro'), ('B', 'Naranja Subrayado'), ('BB', 'Naranja'), ('Bb', 'Naranja Oscuro'), ('C', 'Amarillo Subrayado'), ('CC', 'Amarillo'), ('Cc', 'Amarillo Oscuro'), ('D', 'Verde Subrayado'), ('DD', 'Verde'), ('Dd', 'Verde Oscuro'), ('E', 'Azul Subrayado'), ('EE', 'Azul'), ('Ee', 'Azul Oscuro'), ('F', 'Indigo Subrayado'), ('FF', 'Indigo'), ('Ff', 'Indigo Oscuro'), ('G', 'Morado Subrayado'), ('GG', 'Morado'), ('Gg', 'Morado Oscuro'), ('H', 'Rosa Subrayado'), ('HH', 'Rosa'), ('Hh', 'Rosa Oscuro'), ('I', 'Dorado Subrayado'), ('II', 'Dorado'), ('Ii', 'Dorado Oscuro'), ('J', 'Gris Subrayado'), ('JJ', 'Gris'), ('Jj', 'Gris Oscuro'), ('z', 'Neutral'), ('zz', 'Negro')], default='z', max_length=10),
        ),
    ]
