# Generated by Django 5.2.3 on 2025-07-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabras', to='accounts.usuario')),
            ],
            options={
                'db_table': 'Palabras',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(max_length=100)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='accounts.usuario')),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='dictionary.palabra')),
            ],
            options={
                'db_table': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectura', models.CharField(max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='accounts.usuario')),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='dictionary.palabra')),
            ],
            options={
                'db_table': 'Lecturas',
            },
        ),
        migrations.CreateModel(
            name='Significado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('significado', models.TextField(max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='significados', to='accounts.usuario')),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='significados', to='dictionary.palabra')),
            ],
            options={
                'db_table': 'Significados',
            },
        ),
    ]
