# Generated by Django 5.2.4 on 2025-07-19 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='lectura',
            name='ultima_modificacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='nota',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='nota',
            name='ultima_modificacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='palabra',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='palabra',
            name='ultima_modificacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='significado',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='significado',
            name='ultima_modificacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
