# Generated by Django 5.2.4 on 2025-07-21 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_alter_lectura_autor_alter_nota_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectura',
            old_name='autor',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='autor',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='palabra',
            old_name='autor',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='significado',
            old_name='autor',
            new_name='usuario',
        ),
    ]
