# Generated by Django 5.2.6 on 2025-10-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_rename_autor_lectura_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='lectura_limpia',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
    ]
