# Generated by Django 5.2.6 on 2025-10-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_lectura_lectura_limpia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='lectura_limpia',
            field=models.CharField(max_length=50),
        ),
    ]
