# Generated by Django 5.2.3 on 2025-07-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='accounts.usuario')),
            ],
            options={
                'db_table': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='GrupoPalabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_palabras', to='groups.grupo')),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palabra_grupos', to='dictionary.palabra')),
            ],
            options={
                'db_table': 'Grupos_Palabras',
                'unique_together': {('grupo', 'palabra')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardado', models.BooleanField(default=False)),
                ('estudiando', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_usuarios', to='groups.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_grupos', to='accounts.usuario')),
            ],
            options={
                'db_table': 'Usuarios_Grupos',
                'unique_together': {('usuario', 'grupo')},
            },
        ),
    ]
