# Generated by Django 5.2.4 on 2025-07-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_grupo_fecha_creacion_grupo_ultima_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
