# Generated by Django 5.2.4 on 2025-07-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_grupo_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariogrupo',
            name='guardado',
        ),
    ]
