# Generated by Django 5.2.4 on 2025-07-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_remove_usuariogrupo_guardado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuariogrupo',
            table='settings.AUTH_USER_MODELs_Grupos',
        ),
    ]
