# Generated by Django 5.2.4 on 2025-07-21 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_grupo_autor_alter_usuariogrupo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='autor',
            new_name='usuario',
        ),
    ]
