# Generated by Django 5.2.4 on 2025-08-09 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_rename_autor_grupo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupopalabra',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupopalabra',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuariogrupo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariogrupo',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
