# Generated by Django 5.2.4 on 2025-08-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_grupopalabra_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariogrupo',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
